### ISSUE TITLE
Bold text copy-paste

### ISSUE THREAD

**Issue by leogoody** [Andrew-Chen-Wang/RichEditorView#16]
Hi!
Experiencing an issue with bold text copying and pasting. After pasting of copied text 'b' tag in RE.editor.innerHTML is missing and text is not bold anymore. But tag is being copied: you can paste text in Apple Notes and it will render as bold.
Will appreciate any suggestions how to fix this.

**Comment by Andrew-Chen-Wang** [comment]
I'm not quite understanding this. Are you copying text from the editor view and pasting it again in the editor view (which works for me). Or are you copying bolded text from somewhere else then pasting in the editor view (which isn't supported as of yet I think. I think Google Docs allows it, but it's been awhile since I've seen this package so I'm not sure).

Basically, do you mind clarifying and also giving me a reproduction of what you mean? You can fork this repo and use the Example RichEditorView project to test it out.
